const projects = [
  { title: 'Cloud-Native Appointment Platform', type: 'Personal project · AWS EKS · Terraform', text: 'MERN microservices deployed with Docker and Kubernetes, with Terraform-provisioned AWS infrastructure including VPC, EKS, DocumentDB, and IAM.', color: 'from-emerald-400/30 to-cyan-400/5' },
  { title: 'Checkmate Chess Academy', type: 'Freelance project · Web development', text: 'A freelance web project for a chess academy, focused on providing a clear, professional online presence for its students and community.', color: 'from-violet-400/30 to-fuchsia-400/5' },
  { title: 'Pragati Boutique', type: 'Freelance project · E-commerce', text: 'An e-commerce project for a boutique, designed to present products online and support a smooth shopping experience.', color: 'from-amber-300/30 to-orange-400/5' },
  { title: 'AWS Monitoring Dashboard', type: 'Personal project · CloudWatch', text: 'Monitoring for an auto-scaling web application on EC2, ALB, and Auto Scaling Groups, with CloudWatch dashboards, alarms, and SNS alerts.', color: 'from-sky-400/30 to-blue-400/5' },
];

export default function ProjectsSection() {
  return <section id="projects" className="bg-[#0b192b] px-5 py-24 sm:px-8"><div className="mx-auto max-w-6xl"><p className="font-mono text-sm text-[#63e6be]">03 / selected work</p><div className="mt-5 flex flex-wrap items-end justify-between gap-5"><h2 className="text-3xl font-bold text-white sm:text-5xl">Things I&apos;ve built.</h2><a href="#contact" className="text-sm text-[#63e6be] hover:text-white">Have a project in mind? →</a></div><div className="mt-12 grid gap-5 md:grid-cols-2">{projects.map((project) => <article key={project.title} className={`group rounded-2xl border border-white/10 bg-gradient-to-br ${project.color} p-6 transition hover:-translate-y-1 hover:border-[#63e6be]/50`}><div className="mb-16 h-20 rounded-xl border border-white/10 bg-[#07111f]/40" /><p className="font-mono text-xs text-[#63e6be]">{project.type}</p><h3 className="mt-2 text-2xl font-semibold text-white">{project.title}</h3><p className="mt-3 leading-7 text-slate-400">{project.text}</p></article>)}</div></div></section>;
}
